### ISSUE TITLE
Showing Single friend profile is working now.

### ISSUE THREAD

**Issue by AlanFor301** [CMPUT301F15T13/TheAllSwap#15]
as title but it still need continue work...
eg. 
      1. click on the single friend's inventory starts a new trade needs to be done....
      2. UI needs to be polished, but it doesnt need to be done really quick...

**Comment by smithe0** [comment]
Showing friends profile fully working. Most of friend interaction working with the exception of a few listview updating issues. 

This issue is closed though.
