### ISSUE TITLE
Working on UserFriends activity...

### ISSUE THREAD

**Issue by AlanFor301** [CMPUT301F15T13/TheAllSwap#17]
For now, UserFriend list view contains all user in the local file(not friend list since we haven't get search part done)...
Question: do we need to leave it as it is now? since I think eventually we will have to use elastic search to get all the user friends list result...

**Comment by AlanFor301** [comment]
I'm working on adding Friend to the friend list instead...

**Comment by smithe0** [comment]
For all data that we will be using elastic search for we are storing the data locally for now. Then that locally stored data will be uploaded and recalled if the app is online. 

I've added another view for add friend that browses all existing users that you can click on to add as a friend. Might implement a search option later on.
