### ISSUE TITLE
Trade History

### ISSUE THREAD

**Issue by smithe0** [CMPUT301F15T13/TheAllSwap#27]
Trade history is another area that nobody has worked on yet. I think Daniel wanted to work on it, but if you could say for sure on here that would be excellent. Just so we know what to do and what not to do.

**Comment by smithe0** [comment]
I think the menu navigation button says "previously browsed" which is a pretty misleading name, but there is a skeleton activity for it already.

**Comment by AlanFor301** [comment]
yeah, I just randomly gave it a name when I started. Feel free to change it :)

**Comment by aozero** [comment]
I believe the Pending/Completed Trades activities take care of this. Please reopen if this is not the case.
