### ISSUE TITLE
Compile SDK level and minimum SDK level

### ISSUE THREAD

**Issue by AlanFor301** [CMPUT301F15T13/TheAllSwap#3]
I'm not sure at this point Lixin(Soul) brought up this issue this morning: our compile SDK level is 21(Lollipop) and minimum SDK level is 18 as project required.
Would it be a problem?
the screen shot is in our project Doc file.

**Comment by aozero** [comment]
What problem could there be? I had to download SDK 21 to first build the project when I cloned it but otherwise it's been fine.

**Comment by AlanFor301** [comment]
in the project Doc folder there are two files 
one is our compile sdk (21)
the other one is  minimum sdk (18)

**Comment by AlanFor301** [comment]
Im just not sure if this will cause any problems in the future.

**Comment by aozero** [comment]
I don't think it should, provided people don't change the settings in the future. If we can all use gradle to build the project, we're good.

**Comment by AlanFor301** [comment]
kk. great. issue closed. And I will post issues needs to be done based on our used cases.
