### ISSUE TITLE
User registering/friend adding issue

### ISSUE THREAD

**Issue by aozero** [CMPUT301F15T13/TheAllSwap#38]
Registering two users and adding each other as friends will crash the app (and then the save file will crash the app upon load) after adding the second friend.

Ex. Register U1 and U2, log in as U1 and add U2 as friend. Logout. Log in as U2 and U1 as friend. Crash. App will now not load until save file deleted.

Hard-closing and reopening the app after the first friend-adding allows the second to work correctly.

**Comment by smithe0** [comment]
That's strange. I think I know the issue though I can fix it. It's probably a problem with the singleton not being destroyed properly when you log out.
